language: elixir
elixir:
  - 1.0.5
  - 1.1.1
otp_release:
  - 17.4
  - 18.2.1
matrix:
  include:
    - elixir: 1.2.0
      otp_release: 18.2.1

env: MIX_ENV=test
after_success:
  - mix coveralls.travis
